import { defineType, defineField } from 'sanity';
import { seoFields } from './seo';

export const donateTrustBullet = defineType({
  name: 'donateTrustBullet',
  type: 'object',
  title: 'Trust Bullet',
  fields: [
    defineField({ name: 'title', type: 'string', title: 'Title', validation: (r) => r.required() }),
    defineField({ name: 'desc', type: 'string', title: 'Description', validation: (r) => r.required() }),
  ],
});

export const donateWaysSupportItem = defineType({
  name: 'donateWaysSupportItem',
  type: 'object',
  title: 'Ways To Support Item',
  fields: [
    defineField({ name: 'title', type: 'string', title: 'Title', validation: (r) => r.required() }),
    defineField({ name: 'description', type: 'text', title: 'Description', rows: 4, validation: (r) => r.required() }),
    defineField({
      name: 'image',
      type: 'image',
      title: 'Image',
      options: { hotspot: true },
      description: 'Use photography from /src/assets/mqi-images or equivalent CMS media.',
    }),
    defineField({
      name: 'cta',
      type: 'ctaButton',
      title: 'CTA Button',
      description: 'Button shown under this support option.',
    }),
  ],
});

export const donatePage = defineType({
  name: 'donatePage',
  type: 'document',
  title: 'Donate Page',
  groups: [
    { name: 'hero', title: 'Title + Intro' },
    { name: 'ways', title: 'Ways To Support' },
    { name: 'scholarship', title: 'Zayd bin Thabit Scholarship' },
    { name: 'trust', title: 'Trust' },
    { name: 'hadith', title: 'Hadith' },
    { name: 'closing', title: 'Closing CTA' },
    { name: 'seo', title: 'SEO' },
  ],
  fields: [
    defineField({ name: 'title', type: 'string', title: 'Page Title', group: 'hero', initialValue: 'Support Our Mission' }),
    defineField({ name: 'subtitle', type: 'text', title: 'Page Subtitle', group: 'hero' }),
    defineField({
      name: 'introContent',
      type: 'array',
      title: 'Intro Content',
      group: 'hero',
      of: [{ type: 'block' }],
      description: 'Left-column text shown directly under the page title.',
    }),
    defineField({
      name: 'introImage',
      type: 'image',
      title: 'Intro Image',
      group: 'hero',
      options: { hotspot: true },
      description: 'Right-column image beside intro content.',
    }),
    defineField({
      name: 'introCtaButtons',
      type: 'array',
      title: 'Intro CTA Buttons',
      group: 'hero',
      of: [{ type: 'ctaButton' }],
      validation: (r) => r.max(3),
    }),
    defineField({
      name: 'waysToSupportTitle',
      type: 'string',
      title: 'Section Title',
      group: 'ways',
      initialValue: 'Ways To Support',
    }),
    defineField({
      name: 'waysToSupportItems',
      type: 'array',
      title: 'Support Options',
      group: 'ways',
      of: [{ type: 'donateWaysSupportItem' }],
    }),
    defineField({
      name: 'scholarshipTitle',
      type: 'string',
      title: 'Section Title',
      group: 'scholarship',
      initialValue: 'Zayd bin Thabit Scholarship',
    }),
    defineField({
      name: 'scholarshipSubtitle',
      type: 'text',
      title: 'Section Subtitle',
      group: 'scholarship',
      rows: 3,
    }),
    defineField({
      name: 'scholarshipContent',
      type: 'array',
      title: 'Scholarship Content',
      group: 'scholarship',
      of: [{ type: 'block' }],
      description: 'Rich text supports headings, bullets, and numbered lists.',
    }),
    defineField({
      name: 'scholarshipImages',
      type: 'array',
      title: 'Scholarship Images',
      group: 'scholarship',
      of: [{ type: 'image', options: { hotspot: true } }],
      validation: (r) => r.max(3),
    }),
    defineField({
      name: 'scholarshipCtaButtons',
      type: 'array',
      title: 'Scholarship CTA Buttons',
      group: 'scholarship',
      of: [{ type: 'ctaButton' }],
      validation: (r) => r.max(3),
    }),
    defineField({
      name: 'trustTitle',
      type: 'string',
      title: 'Section Title',
      group: 'trust',
      initialValue: 'Giving with trust',
    }),
    defineField({
      name: 'trustBullets',
      type: 'array',
      title: 'Trust Section',
      group: 'trust',
      of: [{ type: 'donateTrustBullet' }],
    }),
    defineField({
      name: 'trustCtaButtons',
      type: 'array',
      title: 'Trust CTA Buttons',
      group: 'trust',
      of: [{ type: 'ctaButton' }],
      validation: (r) => r.max(2),
    }),
    defineField({
      name: 'hadithTitle',
      type: 'string',
      title: 'Section Title',
      group: 'hadith',
      initialValue: 'Sadaqah Jariyah',
    }),
    defineField({
      name: 'hadith',
      type: 'hadith',
      title: 'Hadith',
      group: 'hadith',
    }),
    defineField({
      name: 'hadithCtaButtons',
      type: 'array',
      title: 'Hadith CTA Buttons',
      group: 'hadith',
      of: [{ type: 'ctaButton' }],
      validation: (r) => r.max(2),
    }),
    defineField({
      name: 'closingCtaTitle',
      type: 'string',
      title: 'Closing CTA Title',
      group: 'closing',
    }),
    defineField({
      name: 'closingCtaSubtitle',
      type: 'text',
      title: 'Closing CTA Subtitle',
      group: 'closing',
      rows: 4,
    }),
    defineField({
      name: 'closingCtaImage',
      type: 'image',
      title: 'Closing CTA Background Image',
      group: 'closing',
      options: { hotspot: true },
    }),
    defineField({
      name: 'closingCtaButtons',
      type: 'array',
      title: 'Closing CTA Buttons',
      group: 'closing',
      of: [{ type: 'ctaButton' }],
      validation: (r) => r.max(3),
    }),
    ...seoFields,
  ],
});
