import { defineType, defineField } from 'sanity';
import { seoFields } from './seo';

export const homepage = defineType({
  name: 'homepage',
  type: 'document',
  title: 'Homepage',
  groups: [
    { name: 'hero', title: 'Hero' },
    { name: 'programs', title: 'Our Programs' },
    { name: 'whyChooseUs', title: 'Why Choose Us' },
    { name: 'testimonials', title: 'Testimonials' },
    { name: 'cta', title: 'CTA Banner' },
    { name: 'seo', title: 'SEO' },
  ],
  fields: [
    defineField({
      name: 'heroEyebrow',
      type: 'string',
      title: 'Hero Eyebrow',
      group: 'hero',
      initialValue: "— Tarbiyah Academy —",
    }),
    defineField({
      name: 'heroTitle',
      type: 'string',
      title: 'Hero Title',
      group: 'hero',
      validation: (r) => r.required(),
    }),
    defineField({
      name: 'heroSubtitle',
      type: 'text',
      title: 'Hero Subtitle',
      group: 'hero',
      rows: 2,
    }),
    defineField({
      name: 'heroCtaButtons',
      type: 'array',
      title: 'Hero CTA Buttons',
      group: 'hero',
      description: 'Link each button to an internal site page (Programs, Donate, etc.) via the Internal page field.',
      of: [{ type: 'ctaButton' }],
    }),
    defineField({
      name: 'programsSectionTitle',
      type: 'string',
      title: 'Programs Section Title',
      group: 'programs',
      initialValue: 'Our Programs',
    }),
    defineField({
      name: 'programsSectionSubtitle',
      type: 'text',
      title: 'Programs Section Subtitle',
      group: 'programs',
    }),
    defineField({
      name: 'featuredPrograms',
      type: 'array',
      title: 'Featured Programs',
      group: 'programs',
      description: 'Specific programs to display on the homepage. Users can filter by category.',
      of: [{ type: 'reference', to: [{ type: 'program' }] }],
    }),
    defineField({
      name: 'viewAllProgramsLabel',
      type: 'string',
      title: 'View All Programs Button Label',
      group: 'programs',
      initialValue: 'View All Programs',
    }),
    defineField({
      name: 'editorialPhotos',
      type: 'array',
      title: 'Editorial accent photos',
      group: 'programs',
      description:
        'Optional lifestyle photos (About page gallery, homepage CTA band, etc.). Up to 4. If empty, default library images are used.',
      validation: (r) => r.max(4),
      of: [{ type: 'image', title: 'Photo', options: { hotspot: true } }],
    }),
    defineField({
      name: 'whyChooseUsSectionTitle',
      type: 'string',
      title: 'Why Choose Us Section Title',
      group: 'whyChooseUs',
      initialValue: 'Why Choose Us',
    }),
    defineField({
      name: 'whyChooseUsSectionSubtitle',
      type: 'text',
      title: 'Why Choose Us Section Subtitle',
      group: 'whyChooseUs',
    }),
    defineField({
      name: 'whyChooseUsItems',
      type: 'array',
      title: 'Why Choose Us Items',
      group: 'whyChooseUs',
      of: [{ type: 'whyChooseUsItem' }],
    }),
    defineField({
      name: 'testimonialsSectionTitle',
      type: 'string',
      title: 'Testimonials Section Title',
      group: 'testimonials',
      initialValue: 'What Families Say',
    }),
    defineField({
      name: 'testimonials',
      type: 'array',
      title: 'Testimonials',
      group: 'testimonials',
      description: 'Short quotes from parents or students.',
      of: [
        {
          type: 'object',
          fields: [
            defineField({ name: 'quote', type: 'text', title: 'Quote', validation: (r) => r.required(), rows: 3 }),
            defineField({ name: 'name', type: 'string', title: 'Name', validation: (r) => r.required() }),
            defineField({ name: 'role', type: 'string', title: 'Role or description', description: 'e.g. Parent of student, Alumni' }),
          ],
          preview: { select: { name: 'name' }, prepare: ({ name }: { name?: string }) => ({ title: name || 'Testimonial' }) },
        },
      ],
    }),
    defineField({
      name: 'ctaTitle',
      type: 'string',
      title: 'CTA Banner Title',
      group: 'cta',
    }),
    defineField({
      name: 'ctaSubtitle',
      type: 'text',
      title: 'CTA Banner Subtitle',
      group: 'cta',
    }),
    defineField({
      name: 'ctaButtons',
      type: 'array',
      title: 'CTA Banner Buttons',
      group: 'cta',
      description: 'Closing banner CTAs should link to internal site pages (not form embeds).',
      of: [{ type: 'ctaButton' }],
    }),
    defineField({
      name: 'footerNote',
      type: 'text',
      title: 'Footer Note',
      group: 'cta',
      rows: 2,
      description: 'Optional short note above or near the CTA (e.g. seasonal message).',
    }),
    ...seoFields,
  ],
});
